### ISSUE TITLE
Error: connect EADDRNOTAVAIL

### ISSUE THREAD

**Issue by feross** [defunctzombie/zuul#119]
Is anyone else seeing this error? I'm not sure what is causing it. I've restarted my machine, so I don't think I'm running any application that are using common ports.

Latest node (0.10.35), latest zuul (1.16.3).

```
> zuul -- test/basic.js

- testing: chrome @ Mac 10.8: 39
- testing: firefox @ Mac 10.6: 34
- queuing: <firefox 34 on Mac 10.6>
- queuing: <chrome 39 on Mac 10.8>

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect EADDRNOTAVAIL
    at errnoException (net.js:904:11)
    at connect (net.js:766:19)
    at net.js:845:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)
    at TunnelCluster.open (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/client.js:74:12)
    at Tunnel._establish (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/client.js:262:17)
    at /Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/client.js:275:14
    at Request._callback (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/client.js:202:13)
    at Request.self.callback (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/node_modules/request/main.js:122:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/node_modules/request/main.js:655:16)
    at Request.init (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/node_modules/request/main.js:126:10)
    at new Request (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/node_modules/request/main.js:105:8)
    at request (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/node_modules/request/main.js:968:11)
    at get_url (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/client.js:190:9)
    at Tunnel._init (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/client.js:210:7)
    at Tunnel.open (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/client.js:269:10)
    at localtunnel (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/localtunnel/client.js:298:12)
    at Server.bouncer_active (/Users/feross/code/webtorrent/node_modules/zuul/lib/setup.js:65:13)
    at Server.listen (net.js:1099:10)
    at setup (/Users/feross/code/webtorrent/node_modules/zuul/lib/setup.js:55:17)
    at setup_test_instance (/Users/feross/code/webtorrent/node_modules/zuul/lib/setup.js:20:9)
    at SauceBrowser.start (/Users/feross/code/webtorrent/node_modules/zuul/lib/SauceBrowser.js:51:23)
    at /Users/feross/code/webtorrent/node_modules/zuul/lib/zuul.js:133:25
    at next (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/batch/index.js:118:7)
    at Batch.end (/Users/feross/code/webtorrent/node_modules/zuul/node_modules/batch/index.js:154:5)
    at /Users/feross/code/webtorrent/node_modules/zuul/lib/zuul.js:137:15
```

**Comment by rase-** [comment]
I haven't seen this happen, at least not lately. Is `localtunnel` playing nice?

**Comment by feross** [comment]
Yeah, haven't seen this in a while. I'll close this issue.

**Comment by cristiandouce** [comment]
Issues started appearing on my CI :dancer: 
@defunctzombie Any clue now if the issue is on docker?

```
Running "exec:test-integration" (exec) task
- testing: chrome @ Mac 10.9: 40
- testing: safari @ Mac 10.10: 8
- testing: firefox @ Windows 2012: 36
- testing: internet explorer @ Windows 2008: 9
- testing: internet explorer @ Windows 2012: 10
- testing: internet explorer @ Windows 2012 R2: 11
- queuing: <safari 8 on Mac 10.10>
- queuing: <chrome 40 on Mac 10.9>
- queuing: <firefox 36 on Windows 2012>
>> 
>> events.js:72
>>         throw er; // Unhandled 'error' event
>>               ^
>> Error: connection refused: localtunnel.me:undefined (check your firewall settings)
```

**Comment by rase-** [comment]
@cristiandouce hmm, haven't seen that.

@defunctzombie any ideas?

**Comment by rase-** [comment]
@cristiandouce localtunnel is completely down at the moment. Hopefully this doesn't show up anymore either when it's back up.

cc @defunctzombie

**Comment by defunctzombie** [comment]
Yes, localtunnel crashed again and did not restart itself. It is back now.

**Comment by parshap** [comment]
Getting this error towards the end of running my tests (i.e., many browsers test fine, then after ~5 minutes zuul crashes).

I know that reliably hosting localtunnel is not an simple task, just adding more information to the issue.

```
Error: connection refused: localtunnel.me:47276 (check your firewall settings)
    at Socket.<anonymous> (/Users/parshap/projects/js-is-integer/node_modules/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/client.js:84:32)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)
    at Socket.Readable.on (_stream_readable.js:708:33)
    at TunnelCluster.open (/Users/parshap/projects/js-is-integer/node_modules/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/client.js:80:12)
    ...
```

**Comment by chemzqm** [comment]
Got the same error, might be a sauce lab limit issue, it works fine when I reduce the test browsers count.
