### ISSUE TITLE
How to contribute ?

### ISSUE THREAD

**Issue by MoOx** [defunctzombie/zuul#168]
I forked the repo to make a PR to fix #167 but when I run `npm test` I get some errors

```console
$ npm test
npm WARN package.json batch@0.5.0 No repository field.
stacktrace-js@0.6.0 node_modules/stacktrace-js

> zuul@2.0.0 test /Users/MoOx/Sync/Development/zuul
> DEBUG=zuul* mocha --ui qunit --timeout 0 --bail -- test/index.js

child_process: customFds option is deprecated, use stdio instead.

    zuul control server active on port 52582 +0ms
  zuul:setup using zuul-localhost to tunnel +45ms
  zuul:setup bouncer active on port 52583 +1ms
  zuul:phantombrowser url http://localhost:52583/__zuul +1ms
  zuul:control-app zuul client took 0.414 seconds to bundle +2s
  zuul:browserify configuring browserify with provided options: undefined +21ms
  zuul:browserify adding to bundle: ["/Users/MoOx/Sync/Development/zuul/test/mocha-bdd/test.js"] +0ms
  zuul:browserify test files took 0.131 seconds to bundle +132ms
  zuul:phantombrowser msg: {"name":"suite :: should pass","type":"test"} +107ms
starting suite :: should pass
  zuul:phantombrowser msg: {"name":"should pass","passed":true,"type":"test_end"} +1ms
passed: should pass
  zuul:phantombrowser msg: {"name":"suite :: should fail","type":"test"} +0ms
starting suite :: should fail
  zuul:phantombrowser msg: {"frames":[{"column":0,"filename":"../../node_modules/browserify/node_modules/assert/assert.js","func":"fail","line":128},{"column":0,"filename":"../../node_modules/browserify/node_modules/assert/assert.js","func":"ok","line":143},{"column":0,"filename":"test.js","func":"{anonymous}()","line":9},{"filename":"http://localhost:52583/__zu
ul/framework.js","func":"{anonymous}()","line":"4308"},{"filename":"http://localhost:52583/__zuul/framework.js","func":"{anonymous}()","line":"4713"},{"filename":"http://localhost:52583/__zuul/framework.js","func":"{anonymous}()","line":"4804"},{"filename":"http://localhost:52583/__zuul/framework.js","func":"next","line":"4638"},{"filename":"http://localhost:525
83/__zuul/framework.js","func":"{anonymous}()","line":"4648"},{"filename":"http://localhost:52583/__zuul/framework.js","func":"next","line":"4586"},{"filename":"http://localhost:52583/__zuul/framework.js","func":"{anonymous}()","line":"4615"},{"filename":"http://localhost:52583/__zuul/framework.js","func":"timeslice","line":"5697"}],"message":"false == true","so
urce":"AssertionError: false == true\n    at fail (http://localhost:52583/__zuul/test-bundle.js:130)\n    at ok (http://localhost:52583/__zuul/test-bundle.js:145)\n    at http://localhost:52583/__zuul/test-bundle.js:1054\n    at http://localhost:52583/__zuul/framework.js:4308\n    at http://localhost:52583/__zuul/framework.js:4713\n    at http://localhost:52583/
__zuul/framework.js:4804\n    at next (http://localhost:52583/__zuul/framework.js:4638)\n    at http://localhost:52583/__zuul/framework.js:4648\n    at next (http://localhost:52583/__zuul/framework.js:4586)\n    at http://localhost:52583/__zuul/framework.js:4615\n    at timeslice (http://localhost:52583/__zuul/framework.js:5697)","type":"assertion"} +1ms
Error: false == true
    fail ../../node_modules/browserify/node_modules/assert/assert.js:128
    ok ../../node_modules/browserify/node_modules/assert/assert.js:143
    {anonymous}() test.js:9
    {anonymous}() http://localhost:52583/__zuul/framework.js:4308
    {anonymous}() http://localhost:52583/__zuul/framework.js:4713
    {anonymous}() http://localhost:52583/__zuul/framework.js:4804
    next http://localhost:52583/__zuul/framework.js:4638
    {anonymous}() http://localhost:52583/__zuul/framework.js:4648
    next http://localhost:52583/__zuul/framework.js:4586
    {anonymous}() http://localhost:52583/__zuul/framework.js:4615
    timeslice http://localhost:52583/__zuul/framework.js:5697

  zuul:phantombrowser msg: {"name":"should fail","passed":false,"type":"test_end"} +5ms
failed should fail
  zuul:phantombrowser msg: {"name":"suite :: should be skipped","type":"test"} +1ms
starting suite :: should be skipped
  zuul:phantombrowser msg: {"passed":false,"stats":{"failed":1,"passed":1,"pending":1},"type":"done"} +0ms
․  zuul control server active on port 52598 +28ms
  zuul:setup using zuul-localhost to tunnel +1ms
  zuul:setup bouncer active on port 52599 +0ms
  zuul:phantombrowser url http://localhost:52599/__zuul +0ms
  zuul:control-app zuul client took 0.315 seconds to bundle +1s
  zuul:browserify configuring browserify with provided options: undefined +20ms
  zuul:browserify adding to bundle: ["/Users/MoOx/Sync/Development/zuul/test/jasmine/test.js"] +0ms
  zuul:browserify test files took 0.008 seconds to bundle +8ms
  zuul:phantombrowser msg: {"name":"suite :: should pass","type":"test"} +103ms
starting suite :: should pass
  zuul:phantombrowser msg: {"name":"suite :: should pass","passed":true,"type":"test_end"} +1ms
passed: suite :: should pass
  zuul:phantombrowser msg: {"name":"suite :: should fail","type":"test"} +0ms
starting suite :: should fail
  zuul:phantombrowser msg: {"actual":true,"frames":[{"filename":"http://localhost:52599/__zuul/client.js","func":"{anonymous}()","line":"1153"},{"filename":"http://localhost:52599/__zuul/client.js","func":"reportFirstSpecFailure","line":"672"},{"filename":"http://localhost:52599/__zuul/client.js","func":"{anonymous}()","line":"694"},{"filename":"http://localhost
:52599/__zuul/framework.js","func":"{anonymous}()","line":"1788"},{"filename":"http://localhost:52599/__zuul/framework.js","func":"{anonymous}()","line":"2343"},{"filename":"http://localhost:52599/__zuul/framework.js","func":"{anonymous}()","line":"2348"},{"filename":"http://localhost:52599/__zuul/framework.js","func":"{anonymous}()","line":"2377"},{"filename":"
http://localhost:52599/__zuul/framework.js","func":"{anonymous}()","line":"2106"},{"filename":"http://localhost:52599/__zuul/framework.js","func":"{anonymous}()","line":"2049"},{"filename":"http://localhost:52599/__zuul/framework.js","func":"{anonymous}()","line":"2378"},{"filename":"http://localhost:52599/__zuul/framework.js","func":"{anonymous}()","line":"2096
"},{"filename":"http://localhost:52599/__zuul/framework.js","func":"{anonymous}()","line":"2092"},{"filename":"http://localhost:52599/__zuul/framework.js","func":"{anonymous}()","line":"2350"},{"filename":"http://localhost:52599/__zuul/framework.js","func":"{anonymous}()","line":"2377"},{"filename":"http://localhost:52599/__zuul/framework.js","func":"{anonymous}
()","line":"2106"},{"filename":"http://localhost:52599/__zuul/framework.js","func":"{anonymous}()","line":"2086"}],"message":"Expected true to be falsy.","type":"assertion"} +0ms
Error: Expected true to be falsy.
    {anonymous}() http://localhost:52599/__zuul/client.js:1153
    reportFirstSpecFailure http://localhost:52599/__zuul/client.js:672
    {anonymous}() http://localhost:52599/__zuul/client.js:694
    {anonymous}() http://localhost:52599/__zuul/framework.js:1788
    {anonymous}() http://localhost:52599/__zuul/framework.js:2343
    {anonymous}() http://localhost:52599/__zuul/framework.js:2348
    {anonymous}() http://localhost:52599/__zuul/framework.js:2377
    {anonymous}() http://localhost:52599/__zuul/framework.js:2106
    {anonymous}() http://localhost:52599/__zuul/framework.js:2049
    {anonymous}() http://localhost:52599/__zuul/framework.js:2378
    {anonymous}() http://localhost:52599/__zuul/framework.js:2096
    {anonymous}() http://localhost:52599/__zuul/framework.js:2092
    {anonymous}() http://localhost:52599/__zuul/framework.js:2350
    {anonymous}() http://localhost:52599/__zuul/framework.js:2377
    {anonymous}() http://localhost:52599/__zuul/framework.js:2106
    {anonymous}() http://localhost:52599/__zuul/framework.js:2086

  zuul:phantombrowser msg: {"name":"suite :: should fail","passed":false,"type":"test_end"} +3ms
failed suite :: should fail
  zuul:phantombrowser msg: {"passed":false,"stats":{"failed":1,"passed":1,"pending":0},"type":"done"} +0ms
․  zuul control server active on port 52614 +27ms
  zuul:setup using zuul-localhost to tunnel +1ms
  zuul:setup bouncer active on port 52615 +0ms
  zuul:phantombrowser url http://localhost:52615/__zuul +0ms
  zuul:control-app zuul client took 0.245 seconds to bundle +1s
  zuul:browserify configuring browserify with provided options: undefined +17ms
  zuul:browserify adding to bundle: ["/Users/MoOx/Sync/Development/zuul/test/mocha-qunit/test.js"] +0ms
  zuul:browserify test files took 0.089 seconds to bundle +90ms
  zuul:phantombrowser msg: {"name":"test 1","type":"test"} +105ms
starting test 1
  zuul:phantombrowser msg: {"name":"test 1","passed":true,"type":"test_end"} +0ms
passed: test 1
  zuul:phantombrowser msg: {"name":"test 2","type":"test"} +1ms
starting test 2
  zuul:phantombrowser msg: {"frames":[{"column":0,"filename":"../../node_modules/browserify/node_modules/assert/assert.js","func":"fail","line":128},{"column":0,"filename":"../../node_modules/browserify/node_modules/assert/assert.js","func":"ok","line":143},{"column":0,"filename":"test.js","func":"{anonymous}()","line":8},{"filename":"http://localhost:52615/__zuul/framework.js","func":"{anonymous}()","line":"4308"},{"filename":"http://localhost:52615/__zuul/framework.js","func":"{anonymous}()","line":"4713"},{"filename":"http://localhost:52615/__zuul/framework.js","func":"{anonymous}()","line":"4804"},{"filename":"http://localhost:52615/__zuul/framework.js","func":"next","line":"4638"},{"filename":"http://localhost:52615/__zuul/framework.js","func":"{anonymous}()","line":"4648"},{"filename":"http://localhost:52615/__zuul/framework.js","func":"next","line":"4586"},{"filename":"http://localhost:52615/__zuul/framework.js","func":"{anonymous}()","line":"4615"},{"filename":"http://localhost:52615/__zuul/framework.js","func":"timeslice","line":"5697"}],"message":"false == true","source":"AssertionError: false == true\n    at fail (http://localhost:52615/__zuul/test-bundle.js:130)\n    at ok (http://localhost:52615/__zuul/test-bundle.js:145)\n    at http://localhost:52615/__zuul/test-bundle.js:1053\n    at http://localhost:52615/__zuul/framework.js:4308\n    at http://localhost:52615/__zuul/framework.js:4713\n    at http://localhost:52615/__zuul/framework.js:4804\n    at next (http://localhost:52615/__zuul/framework.js:4638)\n    at http://localhost:52615/__zuul/framework.js:4648\n    at next (http://localhost:52615/__zuul/framework.js:4586)\n    at http://localhost:52615/__zuul/framework.js:4615\n    at timeslice (http://localhost:52615/__zuul/framework.js:5697)","type":"assertion"} +0ms
Error: false == true
    fail ../../node_modules/browserify/node_modules/assert/assert.js:128
    ok ../../node_modules/browserify/node_modules/assert/assert.js:143
    {anonymous}() test.js:8
    {anonymous}() http://localhost:52615/__zuul/framework.js:4308
    {anonymous}() http://localhost:52615/__zuul/framework.js:4713
    {anonymous}() http://localhost:52615/__zuul/framework.js:4804
    next http://localhost:52615/__zuul/framework.js:4638
    {anonymous}() http://localhost:52615/__zuul/framework.js:4648
    next http://localhost:52615/__zuul/framework.js:4586
    {anonymous}() http://localhost:52615/__zuul/framework.js:4615
    timeslice http://localhost:52615/__zuul/framework.js:5697

  zuul:phantombrowser msg: {"name":"test 2","passed":false,"type":"test_end"} +3ms
failed test 2
  zuul:phantombrowser msg: {"passed":false,"stats":{"failed":1,"passed":1,"pending":0},"type":"done"} +0ms
․  zuul control server active on port 52631 +4s
  zuul:saucebrowser running ipad 4.3 Mac 10.6 +1ms
  zuul:setup using zuul-localhost to tunnel +4ms
  zuul:setup bouncer active on port 52632 +1ms
  zuul:saucebrowser quitting browser +333ms
․

  3 passing (10s)
  1 failing

  1)  mocha-qunit - sauce:
     Uncaught TypeError: Cannot read property 'url' of undefined
      at /Users/MoOx/Sync/Development/zuul/node_modules/zuul-localtunnel/index.js:22:26
      at /Users/MoOx/Sync/Development/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/client.js:312:20
      at /Users/MoOx/Sync/Development/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/client.js:283:20
      at Request._callback (/Users/MoOx/Sync/Development/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/client.js:206:24)
      at Request.self.callback (/Users/MoOx/Sync/Development/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/node_modules/request/main.js:122:22)
      at Request.emit (events.js:110:17)
      at Request.<anonymous> (/Users/MoOx/Sync/Development/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/node_modules/request/main.js:655:16)
      at Request.emit (events.js:129:20)
      at IncomingMessage.<anonymous> (/Users/MoOx/Sync/Development/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/node_modules/request/main.js:617:14)
      at IncomingMessage.emit (events.js:129:20)
      at _stream_readable.js:908:16
      at process._tickCallback (node.js:355:11)



npm ERR! Test failed.  See above for more details.
```

What am I missing ?

I check the README and the wiki and don't found anything to do before trying to run tests.

I am guessing I new some saucelab credentials.

**Comment by vvo** [comment]
Yep you need saucelabs credentials in zuulrc, https://github.com/defunctzombie/zuul/wiki/Zuulrc

then run the tests again

**Comment by MoOx** [comment]
For now I have only a small account available with limited time.
I understand there isn't any credential available with this project. I was thinking [opensauce](https://saucelabs.com/opensauce/) made this possible :/

**Comment by rase-** [comment]
You can get credentials for your fork though, through opensauce.

**Comment by MoOx** [comment]
Ok good to know. Thanks !
Maybe we should add a section about that in the README :)

**Comment by rase-** [comment]
Agreed.

**Comment by rase-** [comment]
Also something to note there would be the fact that Zuul uses https://www.npmjs.com/package/find-nearest-file to find the closest zuulrc to the project, so you don't need to overwrite the one in `$HOME`.

**Comment by defunctzombie** [comment]
Should go in the contributing guide.

**Comment by alexbardas** [comment]
I have a similar problem when running the tests with `npm test`. I've tried to run it on several nodejs versions and the problem persists. I've also added the saucelabs credentials in `.zuulrc` with no luck, but I'd want to run them locally first. Can you please add more details / a guide about how to contribute to the project? I'd really appreciate.

This is the output I get:
```
> DEBUG=zuul* mocha --ui qunit --timeout 0 --bail -- test/index.js


    zuul config: {"ui":"mocha-bdd","capabilities":{"custom-data":{"public":"private"}},"tunnel":"ngrok","browser_retries":6,"browser_output_timeout":-1,"browser_open_timeout":120000,"framework_dir":"***/zuul/frameworks/mocha"} +0ms
  zuul:sauce:internet explorer:11 browser conf: {"browser":"internet explorer","version":"11","capabilities":{"custom-data":{"public":"private"}}} +0ms
  zuul:sauce:internet explorer:11 running +1ms
  zuul:setup using zuul-ngrok to tunnel +180ms
  zuul:setup bouncer active on port 60532 +3ms
  zuul:sauce:internet explorer:11 quitting browser +2s
  zuul:sauce:internet explorer:11 queuing +5ms
  zuul:sauce:internet explorer:11 shutdown +332ms
․  zuul config: {"ui":"jasmine","prj_dir":"***/zuul/test/integration/../fixtures/jasmine","phantom":true,"concurrency":1,"files":["***/zuul/test/integration/../fixtures/jasmine/test.js"],"tunnel":"ngrok","browser_retries":6,"browser_output_timeout":-1,"browser_open_timeout":120000,"framework_dir":"***/zuul/frameworks/jasmine"} +2ms
  zuul:browserify configuring browserify with provided options: undefined +157ms
  zuul:browserify adding to bundle: ["***/zuul/test/fixtures/jasmine/test.js"] +0ms
  zuul control server active on port 60548 +24ms
  zuul:setup using zuul-ngrok to tunnel +3ms
  zuul:setup bouncer active on port 60549 +0ms
  zuul:sauce:internet explorer:11 quitting browser +3ms
  zuul:phantombrowser url https://03b5f60d.ngrok.io/__zuul +332ms
  zuul:sauce:internet explorer:11 shutdown +13ms
․

  1 passing (3s)
  1 failing

  1)  jasmine - phantom:
     Uncaught Error: Not running
...
```

**Comment by alexbardas** [comment]
Nevermind, spent some time and manage to figure it out. If anyone arrives here and is interested, here are some steps:
1. run unit tests locally:
`node_modules/.bin/mocha --ui qunit test/unit/**`
or directly using zuul
`node bin/zuul --ui mocha-qunit --local 8081 -- test/unit/flatten-browser.js`

Some tests defined in the fixtures folder will fail. e.g:
`node bin/zuul --ui mocha-qunit --local 8081 -- test/fixtures/mocha-qunit/**` which has a `assert.ok(false)`

2. even if  `sauce_username` and `sauce_key` are added in `.zuulrc`, `npm test` would still fail.
```
export SAUCE_ACCESS_KEY="%sauce_key%"
export SAUCE_USERNAME="%sauce_username%"
npm test
```
and the tests will be executed remotely on saucelabs
