### ISSUE TITLE
error in cloud testing

### ISSUE THREAD

**Issue by xgbuils** [defunctzombie/zuul#213]
Hi again!

I'm pretty begginner on testing and surely I'm doing something wrong. But I read how to make [cloud testing with karma & sauce](https://docs.saucelabs.com/tutorials/js-unit-testing/) and I had no problem:

``` bash
$ git clone https://github.com/xgbuils/frontpiece.router.git
$ cd frontpiece.router
$ npm install
```
Then I created a `sauce.json` with my user and accesskey:
``` json
{
    "username": "frontpiecerouter",
    "accessKey": "my-acces-key"
}
```
And then I run karma:
``` bash
karma start karma-sauce.conf.js 
INFO [framework.browserify]: 492473 bytes written (0.49 seconds)
INFO [framework.browserify]: bundle built
INFO [karma]: Karma v0.12.36 server started at http://localhost:9876/
INFO [launcher]: Starting browser internet explorer 11 on SauceLabs
INFO [launcher.sauce]: internet explorer 11 session at https://saucelabs.com/tests/792b24a3ee0b4977ae7c6eb7229a7852
WARN [web-server]: 404: /favicon.ico
INFO [IE 11.0.0 (Windows 7 0.0.0)]: Connected on socket eLhJN_XBitLhB0x8KpvT with id 23139134
.
IE 11.0.0 (Windows 7 0.0.0): Executed 1 of 1 SUCCESS (0.557 secs / 0.001 secs)
INFO [launcher.sauce]: Shutting down Sauce Connect
pantalaimon@Lyra:~/prog/web/nodejs/test/frontpiece.router$ 
```
and it works.

But I want to work with zuul. I followed [cloud testing instructions](https://github.com/defunctzombie/zuul/wiki/Cloud-testing) and it doesn't work:

``` bash
$ git clone https://github.com/xgbuils/frontpiece.router.git
$ cd frontpiece.router
$ npm install
```
Then I created a `.zuulrc` with my user and accesskey in project root(This is possible as read on issue #82 .):
``` json
sauce_username: frontpiecerouter
sauce_key: my-access-key
```
And then I run zuul:
``` bash
$ zuul -- test/router_test.js
- testing: internet explorer @ Windows 2012 R2: 11
- queuing: <internet explorer 11 on Windows 2012 R2>
- restarting: <internet explorer 11 on Windows 2012 R2>
- restarting: <internet explorer 11 on Windows 2012 R2>
- restarting: <internet explorer 11 on Windows 2012 R2>
- restarting: <internet explorer 11 on Windows 2012 R2>
- restarting: <internet explorer 11 on Windows 2012 R2>
- restarting: <internet explorer 11 on Windows 2012 R2>
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: [init({"name":"frontpiece.router","tags":[],"browserName":"internet explorer","version":"11","platform":"Windows 2012 R2","appium-version":"1.3.6"})] The environment you requested was unavailable.: Uh oh, you've run out of minutes!
    at /usr/local/lib/node_modules/zuul/node_modules/wd/lib/webdriver.js:129:15
    at Request._callback (/usr/local/lib/node_modules/zuul/node_modules/wd/lib/http-utils.js:85:7)
    at Request.self.callback (/usr/local/lib/node_modules/zuul/node_modules/wd/node_modules/request/request.js:364:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/zuul/node_modules/wd/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/zuul/node_modules/wd/node_modules/request/request.js:1266:12)
```

I do not know if I'm doing something wrong or it is a bug.

Thank you.

**Comment by defunctzombie** [comment]
If you take a look at the error it says: `Uh oh, you've run out of minutes!`. Sounds to me like there is a problem with your saucelabs account.

**Comment by xgbuils** [comment]
Yes, it sounds like. So first I tried before if I had the same problem using karma & sauce. And I don't have this problem. When I use karma, test is ran and is reported in [my saucelabs account](https://saucelabs.com/u/frontpiecerouter)

Is it possible that a account problem depends on the specific tool used?

**Comment by defunctzombie** [comment]
Sounds unlikely that is the case but maybe. Also possible that the platform
being requested is incorrect or requires a specific account.
