### ISSUE TITLE
Error: connection refused: localtunnel.me:<port> (check your firewall settings)

### ISSUE THREAD

**Issue by alekseykulikov** [defunctzombie/zuul#251]
I'm not sure, if this issue is related to zuul or localtunnel, but I get it constantly on local machine and in travis. It does not throw immediately, usually after 1-5 minutes of running.

An example: https://travis-ci.org/treojs/idb-request/builds/92580535
I tried to restart this tests and it throws error randomly sometimes on 5th browser, sometimes on 11th.
Zuul could handle this error, and try to restart localtunnel.

```
- testing: chrome @ Windows 2012: 45
- testing: chrome @ Windows 2012 R2: 46
- testing: firefox @ Windows 2012: 41
- testing: firefox @ Mac 10.8: 42
- testing: internet explorer @ Windows 2012: 10
- testing: internet explorer @ Windows 10: 11
- testing: android @ Linux: 4.4 5.0 5.1
- testing: safari @ Mac 10.10: 8
- testing: safari @ Mac 10.11: 9
- testing: iphone @ Mac 10.10: 7.1 8.0 8.1 8.2 8.3 8.4
- queuing: <chrome 46 on Windows 2012 R2>
- queuing: <firefox 41 on Windows 2012>
- queuing: <firefox 42 on Mac 10.8>
- queuing: <chrome 45 on Windows 2012>
- queuing: <internet explorer 10 on Windows 2012>
- starting: <chrome 46 on Windows 2012 R2>
- starting: <chrome 45 on Windows 2012>
- starting: <internet explorer 10 on Windows 2012>
- starting: <firefox 41 on Windows 2012>
- passed: <chrome 45 on Windows 2012>
- queuing: <internet explorer 11 on Windows 10>
- passed: <internet explorer 10 on Windows 2012>
- queuing: <android 4.4 on Linux>
- passed: <firefox 41 on Windows 2012>
- queuing: <android 5.0 on Linux>
- passed: <chrome 46 on Windows 2012 R2>
- queuing: <android 5.1 on Linux>
- starting: <firefox 42 on Mac 10.8>
- starting: <internet explorer 11 on Windows 10>
- passed: <firefox 42 on Mac 10.8>
- queuing: <safari 8 on Mac 10.10>
- passed: <internet explorer 11 on Windows 10>
- queuing: <safari 9 on Mac 10.11>
- starting: <safari 8 on Mac 10.10>
- starting: <safari 9 on Mac 10.11>
- passed: <safari 8 on Mac 10.10>
- queuing: <iphone 7.1 on Mac 10.10>
- passed: <safari 9 on Mac 10.11>
- queuing: <iphone 8.0 on Mac 10.10>
- starting: <android 4.4 on Linux>
- starting: <android 5.0 on Linux>
- passed: <android 4.4 on Linux>
- queuing: <iphone 8.1 on Mac 10.10>
- passed: <android 5.0 on Linux>
- queuing: <iphone 8.2 on Mac 10.10>
- starting: <android 5.1 on Linux>
- passed: <android 5.1 on Linux>
- queuing: <iphone 8.3 on Mac 10.10>
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: connection refused: localtunnel.me:44225 (check your firewall settings)
    at Socket.<anonymous> (/home/travis/build/treojs/idb-request/node_modules/localtunnel/client.js:84:32)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

**Comment by vvo** [comment]
Got this recently also

**Comment by jhiesey** [comment]
I've been seeing this as well, including when running on Travis (so it's not my local network).

Example here: https://travis-ci.org/jhiesey/stream-http/builds/118192592

**Comment by jhiesey** [comment]
After only seeing failures two days ago I gave my tests another try today and they all passed, so I'd guess it's just localtunnel.me being flaky.

**Comment by calvinmetcalf** [comment]
we've been seeing this pretty consistently on readable streams for iPhone and iPad https://travis-ci.org/nodejs/readable-stream/jobs/122543302

**Comment by lpinca** [comment]
I get this error constantly now, see https://travis-ci.org/primus/eventemitter3/jobs/131226437.

**Comment by lpinca** [comment]
FWIW I've switched to `zuul-ngrok` and the issue seems to be gone.

**Comment by mappum** [comment]
I'm getting this occasionally. Might have to switch to `zuul-ngrok`.

**Comment by calvinmetcalf** [comment]
zuul-ngrok does the trick for readable stream, thanks!

**Comment by vvo** [comment]
Confirming zuul-ngrok is now working well even with parallel builds. @defunctzombie thoughts on making it the default since we do not actively maintain localtunnel?

it would help you get less issues on the long run :)

**Comment by lpinca** [comment]
The ngrok solution no longer works for me with default settings. I use the free plan and ngrok now limits the amount of open tunnels as expected:

```
You may not run more than 2 tunnels over a single ngrok session without an account
```

There is also an [issue](https://github.com/bubenshchykov/ngrok/issues/54) that prevents tunnels from being closed. To work around that the `bind_tls` option must not be set to `both` (default value).
Right now I'm using this configuration:

```yaml
concurrency: 2
tunnel:
  type: ngrok
  bind_tls: true
```

**Comment by vvo** [comment]
Ahah @lpinca I am actually facing the exact same issue and you just solved it for me... Thanks a lot :)

**Comment by lpinca** [comment]
@vvo localtunnel works fine today :)

**Comment by SpainTrain** [comment]
A year later this seems to have returned https://travis-ci.org/SpainTrain/querystring-es3/builds/219168228

However, ngrok and sauce_connect tunnels both encounter failures as well (in the case of those tunnels, indefinite waiting/restarting).

sauce connect issue: https://travis-ci.org/SpainTrain/querystring-es3/builds/219370020

The only way I was able to get this working on travis was setting concurrency to 1 and ensuring only one build is running at a time (this is with the default tunnel).

zuul@3.11.1

**Comment by melihplt** [comment]
Run command line as administrator.
