### ISSUE TITLE
Unhandled `socket hung up` introduced with http-proxy

### ISSUE THREAD

**Issue by cristiandouce** [defunctzombie/zuul#264]
I constantly get this error code when running with `zuul@3.8.0` and `zuul-ngrok@3.0.0`. 

```bash
>> /Users/home/test-lib/node_modules/zuul/node_modules/http-proxy/lib/http-proxy/index.js:119
>>     throw err;
>>     ^
>> 
>> Error: socket hang up
>>     at createHangUpError (_http_client.js:203:15)
>>     at Socket.socketCloseListener (_http_client.js:235:23)
>>     at emitOne (events.js:82:20)
>>     at Socket.emit (events.js:169:7)
>>     at TCP._onclose (net.js:469:12)
>> Exited with code: 1.
```

This doesn't happen with `zuul@3.6.0`, before the introduction of `http-proxy`. If you follow the line of the thrown error:

```js
// ../zuul/node_modules/http-proxy/lib/http-proxy/index.js:119
ProxyServer.prototype.onError = function (err) {
  //
  // Remark: Replicate node core behavior using EE3
  // so we force people to handle their own errors
  //
  if(this.listeners('error').length === 1) {
    throw err;
  }
};
```

**Comment by vvo** [comment]
Yep I had seen this also, see https://github.com/defunctzombie/zuul/pull/256/files. I thought I fixed it but maybe not.

**Comment by cristiandouce** [comment]
bouncy had attached a listener destroying the socket when error occurred by default. That behavior I didn't found in http-proxy module. Not sure either it's the desired behavior but at least there should be an error handler registered.

**Comment by vvo** [comment]
> but at least there should be an error handler registered.

Do you know where we should register it, or if it's an http-proxy task? Maybe there's an issue in their github

**Comment by cristiandouce** [comment]
@vvo I think maybe [here](https://github.com/defunctzombie/zuul/blob/9f34414b2c0c7639b389d32bcfbc68f49b7e6f2f/lib/setup.js#L58-L59).
Like it's said in `http-proxy` code comment:
```js
  // Remark: Replicate node core behavior using EE3
  // so we force people to handle their own errors
```
They expect the users of the lib to handle the errors emitted.

**Comment by vvo** [comment]
Ok, do you think you can provide a PR to zuul to handle this?

**Comment by feross** [comment]
Hey, just saw this issue. I fixed the same issue here (https://github.com/feross/webtorrent-www/commit/cd4cb63575d26457543ac27a6ca01b85342ea715) recently. Hope this helps!

**Comment by vvo** [comment]
It can be fixed here: https://github.com/defunctzombie/zuul/blob/9f34414b2c0c7639b389d32bcfbc68f49b7e6f2f/lib/setup.js
