### ISSUE TITLE
How to use ES6 syntax with zuul test framework

### ISSUE THREAD

**Issue by daveashworth** [defunctzombie/zuul#292]
Using mocha as my test framework, in my `mocha.opts` file I have the following option to tell mocha to use babel as the compiler:

`--compilers js:babel-core/register`

In my test file, my first line is:

`import React from "react";`

And when I run zuul with this test, I see the following output in the console:

```
import React from "react";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

Can someone please point me to where I setup zuul to use babel to make this work properly?

**Comment by daveashworth** [comment]
it looks like you can do this for browserify, but our projects use webpack... 

```
browserify:
  - transform:
      name: babelify
```

Is there another way?

**Comment by vvo** [comment]
@daveashworth not sure zuul is picking mocha.opts, you should ensure it's reading it first

**Comment by daveashworth** [comment]
@vvo: is zuul _supposed_ to pick up `mocha.opts`? That would be nice if so. I didn't mean to imply that I thought it would, only showing that for mocha there _is_ an option to specify compilers. I was hoping there was the same for zuul. I'm currently using `zuul-builder-webpack` to achieve similar results, but was hoping for something built into zuul.

**Comment by vvo** [comment]
It seems it's not pickup up mocha.opts indeed. https://github.com/defunctzombie/zuul/blob/1a3391cfe7699a710cfbf4ad61c0221e3fb331d8/frameworks/mocha/client.js

**Comment by cleverboy32** [comment]
browserify:
  - transform:
      name: babelify   
i use this config get error is this:

```
node_modules/zuul/lib/builder-browserify.js:40
bundler[type](o[type].name, _.omit(o[type], 'name'));
                             
TypeError: Cannot read property 'name' of null
    at register (/Users/cleverboy32/.nvm/versions/node/v6.11.0/lib/node_modules/zuul/lib/builder-browserify.js:40:34)
    at /Users/cleverboy32/.nvm/versions/node/v6.11.0/lib/node_modules/zuul/lib/builder-browserify.js:32:17
    at /Users/cleverboy32/.nvm/versions/node/v6.11.0/lib/node_modules/zuul/node_modules/lodash/index.js:3073:15
    at Function.forIn (/Users/cleverboy32/.nvm/versions/node/v6.11.0/lib/node_modules/zuul/node_modules/lodash/index.js:3362:16)
    at registerable (/Users/cleverboy32/.nvm/versions/node/v6.11.0/lib/node_modules/zuul/lib/builder-browserify.js:30:11)
    at Array.forEach (native)
    at configure (/Users/cleverboy32/.nvm/versions/node/v6.11.0/lib/node_modules/zuul/lib/builder-browserify.js:26:9)
    at initBundler (/Users/cleverboy32/.nvm/versions/node/v6.11.0/lib/node_modules/zuul/lib/builder-browserify.js:98:5)
    at module.exports (/Users/cleverboy32/.nvm/versions/node/v6.11.0/lib/node_modules/zuul/lib/builder-browserify.js:50:27)
    at module.exports (/Users/cleverboy32/.nvm/versions/node/v6.11.0/lib/node_modules/zuul/lib/control-app.js:46:36)
```

please help , thank
