### ISSUE TITLE
iOS Not Working

### ISSUE THREAD

**Issue by saulshanabrook** [defunctzombie/zuul#294]
When I try to run with `--browser-name iphone --browser-version 9.3` it [fails to connect to saucelabs](https://travis-ci.org/saulshanabrook/react-native-webview-crypto/jobs/144807599).

I can see that the [saucelabs config is reported as](https://saucelabs.com/beta/tests/88091396d2af45cd87a61b2af8ef18a7/metadata):

```

"name": "there is only zuul",
"tags": [],
"javascriptEnabled": true,
"tunnel-identifier": "12.1",
"appium-version": "1.5",
"browserName": "iphone",
"version": "9.3",
"platform": "Mac 10.11",
"build": "12"
```

And in the [`selenium-server.log` file](https://saucelabs.com/beta/tests/88091396d2af45cd87a61b2af8ef18a7/logs) it says:

```
Jul 14, 2016 12:03:28 PM org.openqa.grid.selenium.GridLauncher main
INFO: Launching a standalone server
12:03:34.646 INFO - Java: Oracle Corporation 25.92-b14
12:03:34.651 INFO - OS: Mac OS X 10.11 x86_64
12:03:34.675 INFO - v2.28.0, with Core v2.28.0. Built from revision 18364
12:03:34.973 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4443/wd/hub
12:03:34.975 INFO - Version Jetty/5.1.x
12:03:34.978 INFO - Started HttpContext[/selenium-server,/selenium-server]
12:03:35.073 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@77f03bb1
12:03:35.073 INFO - Started HttpContext[/wd,/wd]
12:03:35.074 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
12:03:35.074 INFO - Started HttpContext[/,/]
12:03:35.087 INFO - Started SocketListener on 0.0.0.0:4443
12:03:35.087 INFO - Started org.openqa.jetty.jetty.Server@7106e68e
12:03:35.713 INFO - Executing: org.openqa.selenium.remote.server.handler.Status@e3ea68e at URL: /status)
12:03:35.728 INFO - Done: /status
12:03:36.505 INFO - Executing: [new session: {proxy={proxyAutoconfigUrl=http://12..., webdriver.remote.quietExceptions=true, browserName=iphone, javascriptEnabled=true}] at URL: /session)
12:03:37.423 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.28.0', revision: '18364', time: '2013-01-10 00:47:46'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.8.0_92'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:174)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:112)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:89)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:89)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:63)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:201)
	at org.openqa.selenium.remote.server.JsonHttpRemoteConfig.handleRequest(JsonHttpRemoteConfig.java:192)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:201)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:167)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:139)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:677)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:914)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.28.0', revision: '18364', time: '2013-01-10 00:47:46'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.8.0_92'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:67)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:51)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:213)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:167)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:57)
	... 8 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.28.0', revision: '18364', time: '2013-01-10 00:47:46'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11', java.version: '1.8.0_92'
Driver info: driver.version: IPhoneDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:527)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:216)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:111)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
	at org.openqa.selenium.iphone.IPhoneDriver.<init>(IPhoneDriver.java:80)
	at org.openqa.selenium.iphone.IPhoneDriver.<init>(IPhoneDriver.java:91)
	at org.openqa.selenium.iphone.IPhoneDriver.<init>(IPhoneDriver.java:100)
	at org.openqa.selenium.iphone.IPhoneDriver.<init>(IPhoneDriver.java:104)
	... 13 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:4723 refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:190)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:151)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.openqa.selenium.remote.HttpCommandExecutor.fallBackExecute(HttpCommandExecutor.java:331)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:310)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:506)
	... 20 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:127)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	... 28 more
12:03:37.429 WARN - Exception: Connection refused
```

**Comment by vvo** [comment]
Hello I fail at deciphering the selenium error log, is there any valuable information here?

**Comment by saulshanabrook** [comment]
At first I saw `Driver info: driver.version: unknown` and thought that was the problem, but looking at the trace longer, it doesn't seem to be it.

 I have the same exact build [working with android](https://travis-ci.org/saulshanabrook/react-native-webview-crypto/jobs/144807602), so I am just unsure how to debug this further.

Does anyone have the latest version of zuul working on an iphone device?

**Comment by vvo** [comment]
Can you try iphone 9.2 maybe?

**Comment by saulshanabrook** [comment]
I just gave that a go: https://travis-ci.org/saulshanabrook/react-native-webview-crypto/jobs/145135398

It looks like maybe something with the tunnel isn't working? 

![screen shot 2016-07-15 at 6 50 08 pm](https://cloud.githubusercontent.com/assets/1186124/16890479/0e1ddf82-4abd-11e6-94d3-f3eb563fe507.png)

**Comment by saulshanabrook** [comment]
Seems like Karma users are having similar troubles https://github.com/karma-runner/karma-sauce-launcher/issues/76#issuecomment-228223261

**Comment by saulshanabrook** [comment]
Does anyone have any version of iOS testing working with a local tunnel on the latest version of zuul?

**Comment by saulshanabrook** [comment]
I got around this by not using sauce connect and [using](https://github.com/saulshanabrook/react-native-webview-crypto/blob/b753f94f1c62a5041c6253d6958edb0cdd0c4430/test/zuul.config.js) localtunnel [with https](https://github.com/rase-/zuul-localtunnel/pull/1).
